spring:

    profiles.active: dev


    datasource: 
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/parking-car-db
        username: postgres
        password: 123456

    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate.ddl-auto: create-drop

server.port: 8080